config:
  client_id: 101
  queue_details:
  - queue_id: phone-bill
    details:
      save_allowed: true
  - queue_id: internet-bill
    details:
      start_of_week: sunday
  - queue_id: default
    details:
      save_allowed: false
      start_of_week: monday
      fte_formula: ChatVol/ (AHT*Concurrency*Utilization)
